=== Joonaspraks/burger-finder/frontend/photosSchema.json
{
	"type": "array",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"description": "",
	"uniqueItems": true,
	"items": {
		"type": "object",
		"required": ["id", "created_at", "prefix", "suffix", "width", "height"],
		"properties": {
			"id": {
				"type": "string",
				"minLength": 1
			},
			"created_at": {
				"type": "string",
				"minLength": 1
			},
			"prefix": {
				"type": "string",
				"minLength": 1
			},
			"suffix": {
				"type": "string",
				"minLength": 1
			},
			"width": {
				"type": "number"
			},
			"height": {
				"type": "number"
			},
			"classifications": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		}
	}
}

=== Joonaspraks/burger-finder/frontend/examplePhotosRes.json
[
	{
		"id": "614a0975359bbb1550185c89",
		"created_at": "2021-09-21T16:33:57.000Z",
		"prefix": "https://fastly.4sqi.net/img/general/",
		"suffix": "/39906_HLr-9fpiakBWOii_d5mlgDfAVpzryZGB6dPYBF4-SMY.jpg",
		"width": 1080,
		"height": 810
	},
	{
		"id": "60f5a20d5c7b085b8a7f8e83",
		"created_at": "2021-07-19T16:02:21.000Z",
		"prefix": "https://fastly.4sqi.net/img/general/",
		"suffix": "/39906_lmpmg6IcqBLin48tvDuTP-NFCyVEVychj7qUZDNiZcs.jpg",
		"width": 1080,
		"height": 810
	},
	{
		"id": "5da339109472350008e1d250",
		"created_at": "2019-10-13T14:47:44.000Z",
		"prefix": "https://fastly.4sqi.net/img/general/",
		"suffix": "/14084990_ntySOe1rwVexp875gP_2FIMMFUyGfIsookMKGhheQh4.jpg",
		"width": 1440,
		"height": 1920
	},
	{
		"id": "5d56ab933abe8f00082e5fcb",
		"created_at": "2019-08-16T13:11:47.000Z",
		"prefix": "https://fastly.4sqi.net/img/general/",
		"suffix": "/32281188_z_qRpdGHOQX6cih3OAruCyDrN8hNwzr63c6KwRBzKgA.jpg",
		"width": 1425,
		"height": 1900,
		"classifications": ["food"]
	},
	{
		"id": "5cc0882cb6eedb002cdef4ca",
		"created_at": "2019-04-24T16:00:44.000Z",
		"prefix": "https://fastly.4sqi.net/img/general/",
		"suffix": "/39906_3MloiWCNTR7dqHQXIevZ9rNrIln30HQqJ3TWEfDu4uw.jpg",
		"width": 1900,
		"height": 1425
	},
	{
		"id": "5bfeb1eec66666002c9d9c2c",
		"created_at": "2018-11-28T15:19:10.000Z",
		"prefix": "https://fastly.4sqi.net/img/general/",
		"suffix": "/39906_YHSUG-ygr-VYrwS3egUg__gKTBxeC5ysncYwCJfz_eA.jpg",
		"width": 1900,
		"height": 1425
	}
]
